### ISSUE TITLE
Can this be used to "stream" midi via a Virtual Midi Buffer?

### ISSUE THREAD

**Issue by ghost** [OIIOIIOI/hxmidilib#6]
I am wondering if I can use this library to create an application that sends MIDI events to other applications via something like Jack.  I.e. can I use this library the same way I'd use RTMidi?

**Comment by sylvere-a** [comment]
Sorry, I have no idea...
Maybe the original author's page can help you: https://code.google.com/archive/p/as3midilib/

**Comment by ghost** [comment]
No worries.  Thanks for the redirect, i'll mark it as closed.
